### PR TITLE
Adds key for platform-insights external workers

### PR DESCRIPTION
**Pull request by klakin-pivotal**

### CODE REVIEW

**Comment by klakin-pivotal** [comment]
DCO bot says:

> Commit sha: 6a280fb, Author: Kenneth Lakin, Committer: GitHub; The sign-off is missing.

Do I _seriously_ need to add a signoff for my own commit?

**Comment by cirocosta** [comment]
Hey @klakin-pivotal , yeah. you still need to do it 😬

**Comment by vito** [comment]
@klakin-pivotal Yes, that's how every DCO process works. There are instructions [detailed in the failing check](https://github.com/concourse/prod/pull/27/checks?check_run_id=189051583) that you can literally just copy-paste. It only takes a second to follow.

In this case we can just skip it. I don't think we need to apply DCO to this repo as there's not really any code to license here in the first place. It's just config. The DCO bot is only kicking in here because we have it enabled on across the entire organization so we don't forget it in any new repos.

**Comment by klakin-pivotal** [comment]
> Yes, that's how every DCO process works.

I would have expected that me submitting a PR (sign-off `#2`) containing a single commit that I authored (sign-off `#1`) would have been enough signoffs to signal Developer Consent. :heart:

Anyway, I would have added sign-off `#3` on Friday, but I only just got back into the office today. Thanks much for merging this in! :)

**Pull request merged**
